core/urls.py
from django.urls import path
from . import views


app_name='core'
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home_view, name='home_view'),
    path('edit/<int:id>/', views.edit, name='edit'),
    path('delete/<int:id>/', views.delete, name='delete'),
    path('logout/', views.logout_view, name='logout_view'),
    path('test/', views.test_view, name='test_view'),
]

orange_note/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Note(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 50, blank=True, null=True)
    note = models.TextField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    

core/forms.py
from django import forms  
from django.contrib.auth.models import User  
from django.contrib.auth.forms import UserCreationForm  
from django.core.exceptions import ValidationError  
# from django.forms.fields import EmailField  
from django.forms.forms import Form 
from .models import Note 

  
class CustomUserCreationForm(UserCreationForm):  
    username = forms.CharField(label='Username', 
                                min_length=3, 
                                max_length=150, 
                                widget=forms.TextInput(attrs={'class': "username", 'id': "username", 'placeholder':"username"}))  
    email = forms.EmailField(label='Email',
                                min_length=3, 
                                max_length=150, 
                                widget=forms.TextInput(attrs={'class': "mail", 'id':"mail", 'placeholder':"email"}))  
    password1 = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(attrs={'class': "password", 'id':"pword", 'placeholder':"password"}))  
    password2 = forms.CharField(label='Confirm Password', 
                                widget=forms.PasswordInput(attrs={'class': "confirmPassword", 'id':"confirm_password", 'placeholder':"confirm password"}))
    field_order=['email', 'username', 'password1', 'password2']

    def username_clean(self):  
        username = self.cleaned_data['username'].lower()  
        new = User.objects.filter(username = username)  
        if new.count():  
            raise ValidationError("User Already Exist") 
        return username  
  
    def email_clean(self):  
        email = self.cleaned_data['email'].lower()  
        new = User.objects.filter(email=email)  
        if new.count():  
            raise ValidationError("Email Already Exist")  
        return email  
  
    def clean_password2(self):  
        password1 = self.cleaned_data['password1']  
        password2 = self.cleaned_data['password2']  
  
        if password1 and password2 and password1 != password2:  
            raise ValidationError("Password don't match")  
        return password2  
  
    def save(self, commit = True):  
        user = User.objects.create_user(  
            self.cleaned_data['username'],  
            self.cleaned_data['email'],  
            self.cleaned_data['password1']  
        )  
        return user  


class AuthForm(forms.Form):
    email = forms.EmailField(label='Email',
                                min_length=3, 
                                max_length=150, 
                                widget=forms.TextInput(attrs={'class': "mail2", 'id':"email", 'placeholder':"email"}))  
    password = forms.CharField(label='Password', 
                                widget=forms.PasswordInput(attrs={'class': "password2", 'id':"password", 'placeholder':"password"})) 


class NoteForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['note'].label = ""

    class Meta:
        model = Note
        fields = ['title', 'note']
        widgets = {
            'title': forms.TextInput(attrs={
                'class': "title-input",
                'placeholder': 'Enter title',
                'value':''
                }),
            'note': forms.Textarea(attrs={ 
                'hidden': 'hidden',
                'name':'note',
                'class':'note-textarea',
                'value':''
                })
        }

core/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from django.contrib import messages
from .forms import CustomUserCreationForm, AuthForm, NoteForm
from django.urls import reverse
from django.core.paginator import Paginator
from .models import Note
from django.http import JsonResponse
from pprint import pprint
import json

# Create your views here.
def index(request):
    if request.user.is_authenticated:
        return redirect(reverse('core:home_view'))
    signup_form = CustomUserCreationForm(request.POST or None)
    signIn_form = AuthForm(request.POST or None)

    context = {
        'signup_form': signup_form,
        'signIn_form': signIn_form,
    }

    if signup_form.is_valid():
        user_obj = signup_form.save()
        messages.success(request, 'Sign up successful, you can now sign in!!!')
        home = reverse('core:home_view')
        return redirect(home)
    else:
        messages.error(request, 'Something went wrong try again!!!')
        
    if signIn_form.is_valid():
        email = request.POST.get('email')
        password = request.POST.get('password')
        user = authenticate(request, username=email, password=password)
        if user is None:
            messages.error(request, 'Invalid username or password!!!')
            return render(request, 'core/index.html', context)
        login(request, user)
        messages.success(request, 'You are logged in!!!')
        home = reverse('core:home_view')
        return redirect(home)

    return render(request, 'core/index.html', context)

    

@login_required
def home_view(request):
    note_list = Note.objects.all().order_by('-id')
    paginator = Paginator(note_list, 4)

    page_number = request.GET.get('page')

    if page_number:
        notes = paginator.get_page(page_number)
    else:
        notes = paginator.get_page(1)

    # pprint(page_obj)
    is_ajax = request.headers.get('X-Requested-With') == 'XMLHttpRequest'
    if is_ajax:
        if request.method == "POST":
            data = json.load(request)
            form = NoteForm(data) 
            title = data.get('title')
            note = data.get('note')
            if title or len(note) > 11:
                note = form.save(commit=False)
                if note.user_id is None:
                    note.user_id = request.user.id
                note.save() 
        else:
            pass  
    form = NoteForm()
    context = {
        'form':form,
        'notes': notes
    }
    return render(request, 'core/home.html', context)

@login_required
def delete(request, id):
    pass

def edit(request, id):
    
    return redirect(reverse('core:home_view'))


@login_required
def logout_view(request):
    if request.method == "POST":
        logout(request)
        return redirect("core:index")
    return render(request, "core/logout.html")

def test_view(request):
    form = CustomUserCreationForm()
    context = {
        'form': form
    }
    # form.order_fields(field_order=['email', 'username', 'password1', 'password2'])
    return render(request, 'core/test.html', context)

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Orange Notes</title>
    <link rel="stylesheet" href="{% static 'richtexteditor/rte_theme_default.css' %}" />
    <link rel="stylesheet" href="{% static 'css/indexx.css' %}">
    <script type="text/javascript" src="{% static 'richtexteditor/rte.js' %}"></script>
    <script type="text/javascript" src=" {%static 'richtexteditor/plugins/all_plugins.js' %}"></script>
</head>
<body>
    {% if messages %}
        <ul class="messages msg">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    
    {% block content  %}


    {% endblock content %}
    <script type='module' src="{% static 'js/index.js' %}"></script>
</body>
</html>

templates/core/home.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
    <div class="container home-container">
        <a href="{% url 'core:logout_view' %}">
            <button class="orange-image" >Sign-Out</button>
        </a>
        <div class="flex-box1">
            <div class="search">
                <button type="button" class="search-btn"><img src="{% static 'img/search.svg' %}"/></button>
                <input type="search" name="search" id="search" placeholder="search...">
            </div>
            <div>
                <ul>
                    {% for note in notes %}
                        <li>
                            <h3 class="title">{{ note.title }}</h3>
                            <p class="note">{{ note.note }}</p>
                            <div class="edit-delete">
                                <div class="edit">
                                    <a href="/edit/{{note.id}}"><img src="{% static 'img/edit.svg' %}" alt="" width="15"></a>
                                    
                                </div>
                                <div class="del">
                                    <a href="/delete/{{note.id}}"><img src="{% static 'img/delete.svg' %}" alt="" width="25"></a>
                                </div>
                            </div>
                        </li>
                        {% comment %} <a href="/play-video?video_id={{video.id}}">
                            <video width="160" height="200" controls>
                                <source src="{{video.video_path.url}}" type="video/mp4" >
                            </video>
                        </a> {% endcomment %}
                    {% endfor %}
                </ul>
                <div class="paginate">
                    {% if notes.has_previous %}
                        {% comment %} <a href="?page=1">&laquo; first</a> {% endcomment %}
                        <a href="?page={{ notes.previous_page_number }}" class='prev'><button>prev</button></a>
                    {% else %}
                        <button>first</button>
                    {% endif %}

                    {% comment %} <span class="current">
                        Page {{ notes.number }} of {{ notes.paginator.num_pages }}.
                    </span> {% endcomment %}

                    {% if notes.has_next %}
                        <a href="?page={{ notes.next_page_number }}" class='next'><button>next</button></a>
                        {% comment %} <a href="?page={{ notes.paginator.num_pages }}">last &raquo;</a> {% endcomment %}
                    {% else %}
                        <button>last</button>
                    {% endif %}
                    {% comment %} <button>prev</button>
                    <button>next</button> {% endcomment %}
                </div>
            </div>
        </div>
        <form action="." method="POST" class="content-form">
            {% comment %} {%csrf_token%} {% endcomment %}
            <input type="hidden" name="csrfmiddlewaretoken" value="{{csrf_token}}" class='token'>
            <div class="flex-box2">
                <div class="enter_note">
                    {{ form.as_p }}
                    <div id="div_editor1" class="editor">
                        {% comment %} <p>This is a default toolbar demo of Rich text editor.</p>
                        <p><img src='../img/landing-page.png' width="200"/></p> {% endcomment %}
                    </div>
                </div>
                <button type="submit" class="btn content-btn" >Save</button>
            </div>
        </form>
    </div>
  </main>
    <script type="text/javascript">window.CSRF_TOKEN = "{{ csrf_token }}";</script>

    <script type='module' src="{% static 'js/index.js' %}"></script>

    <script>
        var editor1 = new RichTextEditor("#div_editor1");
	//editor1.setHTMLCode("Use inline HTML or setHTMLCode to init the default content.");
    </script>
{% endblock content %}

templates/core/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<main>
    {% if messages %}
    {% endif %}
    <div class="overlay hide fadeIn">
      <form action="" method="post" class="signup hide">
        <div class="close fadeOut">&times;</div>
          {% csrf_token %}
          {{ signup_form.as_p }}
        {% comment %} <div>
          <label for="mail">Email</label>
          <input type="email" id="mail" class="mail" placeholder="email" value="">
        </div>
        <div>
          <label for="username">Username</label>
          <input type="text" id="username" placeholder="username" class="username">
        </div>
        <div>
          <label for="pword">Password</label>
          <input type="password" id="pword" class="password" placeholder="password">
        </div>
        <div>
          <label for="confirm_password">Confirm Password</label>
          <input type="password" id="confirm_password" placeholder="confirm password" class="confirmPassword">
        </div> {% endcomment %}
        <div class="div-button">
          <button type="submit" class="btn form-btn signup-btn">Sign-Up</button>
        </div>
      </form>

      <form action="." method="post" class="signIn hide">
        <div class="close">&times;</div>
          {% csrf_token %}
          {{ signIn_form.as_p }}
        {% comment %} <div>
          <label for="email">Email</label>
          <input type="email" id="email" class="mail2" placeholder="email">
        </div>
        <div>
          <label for="password">Password</label>
          <input type="password" id="password" class="password2" placeholder="password">
        </div> {% endcomment %}
        <div class="div-button">
          <button type='submit' class="btn form-btn signIn-btn">Sign-In</button>
        </div>
      </form>
    </div>


    <div class="container">
      <!-- <a href="./html/home.html"> -->
        <button class="orange-image signIn">Sign-In</button>
      <!-- </a> -->
      <div class="grey-image"></div>
      <div class="content-container">
        <div class="landing-msg">
          <h1>Orange Your Thoughts</h1>
          <div>
            <button class="btn get-started">Get started</button>
            <p>Take notes the simple way for free. Forever</p>
          </div>
        </div>
        <div class="landing-img">
          <img src="{% static 'img/landing-page.png' %}" alt="img" width="300">
        </div>
      </div>
      <div>
        <img src="{% static 'img/landing-page.png' %}" alt="img" width="350">
      </div>
    </div>
  </main>

{% endblock content %}

templates/core/logout.html
{% extends "base.html" %}
{% load static %}

{% block content %}

{% if request.user.is_authenticated %}
    <div class="logout-center">
        <div class="logout">
            <p>Are you sure you want to logout?</p>
            <div class="res">
                <form action="" method="POST" class="m-10">
                    {% csrf_token %}
                    <div >
                        <button type='submit'>Yes</button>
                    </div>
                </form>
                <form method="POST" action="{{ request.META.HTTP_REFERER }}">
                    {% csrf_token %}
                    {% comment %} <input type="hidden" name="next" value="{{ request.META.HTTP_REFERER }}"> {% endcomment %}
                    <button type="submit">No</button>
                </form>
            </div>
        </div>
    </div>
{% else %}
    <div class="logout-center">
        <div class="logout">
            <p>You're not logged in. Would you like to <a href='/login/'>login</a>?</p>
        </div>
    </div>

{% endif %}

{% endblock %}

templates/core/test.html
{% extends 'base.html' %}

{% block content %}

<div style='margin-top:30px;'>
    <form action='.' method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button style='margin-top:10px;' type='submit' >Create article</button>
    </form>
</div>

{% endblock content %}